
spring:   
  datasource:   
    url: jdbc:mysql://os-offshore-ms-db.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/testdb
    username: msuser
    password: msuser123
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    addresses: 172.30.47.87:5672
    host: rabbitmq.test.svc
    port: 5672
    username: spring
    password: spring